# Generated by Django 5.0.7 on 2024-08-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_transaction', models.DateTimeField(auto_now=True)),
                ('last_transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_transaction_type', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Accounting',
                'ordering': ['last_transaction'],
            },
        ),
    ]
