# Generated by Django 5.0.7 on 2024-08-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
